version: "3.8"

# environment
x-env-db: &db-env
  POSTGRES_DB: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "root"

x-volumes: &app-env
  ALLOWED_HOSTS: "*"
  JWT_SECRET_KEY: "fastapi_sql_secret_key"

  DB_URL: "postgresql+asyncpg://root:password@db:5432/postgres"
  DEBUG: "True"

  <<: *db-env

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nayanbiswas/fastapi_sql_server:latest
    container_name: fastapi_sql_server
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    environment:
      <<: *app-env
    # env_file: .env
    volumes:
      - ./:/code
    depends_on:
      - db
      - redis
    networks:
      - fastapi_sql_tier

  worker:
    image: nayanbiswas/fastapi_sql_server:latest
    container_name: fastapi_sql_worker
    restart: unless-stopped
    command: "watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- \
      celery --app=worker.main:celery_app worker --beat --loglevel=debug"
    environment:
      <<: *app-env
    volumes:
      - ./:/code
    depends_on:
      - db
      - redis
    networks:
      - fastapi_sql_tier

  db:
    image: postgres:16
    container_name: fastapi_sql_db
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - fastapi_sql_tier
    volumes:
      - fastapi_sql_db:/var/lib/postgresql/data
    environment:
      <<: *db-env

  redis:
    image: redis:7
    container_name: fastapi_sql_redis
    restart: unless-stopped
    networks:
      - fastapi_sql_tier
    volumes:
      - fastapi_sql_redis:/data

volumes:
  fastapi_sql_db:
    driver: local
  fastapi_sql_redis:
    driver: local

networks:
  fastapi_sql_tier:
    driver: bridge
